name: Docker Image CI

on:
  push:
    branches: master
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name : Checkout
      uses: actions/checkout@v2
    
    - name: Build with Maven
      run: mvn install -DskipTests --file pom.xml
    
    - name: Set Up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set Up Buildx
      uses: docker/setup-buildx-action@v1

#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag schemacrawler-additional-lints:$(date +%s)
#      env:
#          SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
#          SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
#          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64,linux/386
        push: true
        tags: "latest,${{ steps.condval.outputs.value }}"
        tag_with_ref: true
    
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
