name: Docker Image CI

on:
  push:
    branches: master
    tags: '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name : Checkout
      uses: actions/checkout@v2
      
    - name: Prepare
      id: prep
      run: |
          DOCKER_IMAGE=mbarre/schemacrawler-additional-lints
          VERSION=noop
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            TAGS="${DOCKER_IMAGE}:latest,${DOCKER_IMAGE}:${VERSION}"
          else
            TAGS="${DOCKER_IMAGE}:latest"
          fi
          echo ::set-output name=tags::${TAGS}
    
    - name: Build with Maven
      run: mvn install -DskipTests --file pom.xml
    
    - name: Set Up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set Up Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push from master
      id: docker_build_master
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64,linux/386
        push: true
        tags: ${{ steps.prep.outputs.tags }}
    
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
